site_name: 'vrijtap'

nav:
- 'Home': 'index.md'
- 'Manual': 'manual.md'
- 'Raspberry Pi':
  - 'Installation': 'raspberry-pi/installation.md'
  - 'Circuit': 'raspberry-pi/circuit.md'
- 'Technical Documentation':
  - 'Backend [Golang]': 'technical-documentation/backend.md'

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash