site_name: 'vrijtap'

nav:
- 'Home': 'index.md'
- 'Manual': 'manual.md'
- 'Arduino':
  - 'Installation': 'arduino/installation.md'
  - 'Circuit': 'arduino/circuit.md'
  - 'Classes': 'arduino/classes.md'
- 'Raspberry Pi':
  - 'Installation': 'raspberry-pi/installation.md'
  - 'Circuit': 'raspberry-pi/circuit.md'
- 'Artificial Intelligence':
  - 'Model': 'artificial-intelligence/model.md'
- 'Webiste':
  - 'Installation': 'website/installation.md'

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - c++
